# Generated by Django 5.2 on 2026-02-11 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('referrals_made', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('announcement_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('danger', 'Danger')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('show_popup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_withdrawal', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('signup_bonus', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('daily_bonus', models.DecimalField(decimal_places=2, default=0.1, max_digits=10)),
                ('referral_bonus', models.DecimalField(decimal_places=2, default=0.5, max_digits=10)),
                ('referral_commission', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('max_tasks_per_day', models.IntegerField(default=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('referral_enabled', models.BooleanField(default=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('site_name', models.CharField(default='YTEarn', max_length=100)),
                ('paypal_enabled', models.BooleanField(default=True)),
                ('crypto_enabled', models.BooleanField(default=True)),
                ('bank_transfer_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='FraudDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraud_type', models.CharField(choices=[('multiple_accounts', 'Multiple Accounts'), ('vpn_detected', 'VPN Detected'), ('suspicious_activity', 'Suspicious Activity'), ('bot_detected', 'Bot Detected'), ('rapid_tasks', 'Rapid Task Completion'), ('same_ip', 'Same IP Multiple Accounts')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('action', models.CharField(max_length=50)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
