# Generated by Django 5.2 on 2026-04-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_paymentaccount_packagepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepayment',
            name='package_name',
            field=models.CharField(choices=[('normal', 'Normal'), ('super', 'Super'), ('premium', 'Premium'), ('high_octane', 'High Octane')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='packagepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=10),
        ),
    ]
